CeeLearnAndDo/Controllers/AdminReferencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CeeLearnAndDo.Models;
using System.IO;

namespace CeeLearnAndDo.Controllers
{
    [RoutePrefix("beheer/referenties")]
    [Route("{action=index}")]
    public class AdminReferencesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: beheer/referenties
        public ActionResult Index()
        {
            return View(db.References.ToList());
        }

        // GET: beheer/referenties/5
        [Route("{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reference reference = db.References.Find(id);
            if (reference == null)
            {
                return HttpNotFound();
            }
            return View(reference);
        }

        // GET: beheer/referenties/nieuw
        [Route("nieuw")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: beheer/referenties/nieuw
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("nieuw")]
        public ActionResult Create([Bind(Include = "Id,Title,Description,URL,ImagePath,CreatedAt,UpdatedAt")] Reference reference, HttpPostedFileBase ImagePath)
        {
            if (ModelState.IsValid)
            {
                // generate random guid string as fileName
                Guid g = Guid.NewGuid();
                string fileName = Convert.ToBase64String(g.ToByteArray());
                fileName = fileName.Replace("=", "");
                fileName = fileName.Replace("+", "");
                fileName = fileName.Replace("/", "");
                fileName = fileName + "-reference" + Path.GetExtension(ImagePath.FileName);

                // save image
                string path = Path.Combine(Server.MapPath("~/UploadedFiles/ReferenceImages"), fileName);
                ImagePath.SaveAs(path);
                reference.ImagePath = fileName;

                // add reference properties
                db.References.Add(reference);

                // remove http:// or https:// from posted URL
                reference.URL = reference.URL.Replace("https://", "").Replace("http://", "");

                // at dates
                reference.CreatedAt = DateTime.Now;
                reference.UpdatedAt = DateTime.Now;

                // save new reference
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reference);
        }

        // GET: beheer/referenties/wijzigen/5
        [Route("wijzigen/{id:int}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reference reference = db.References.Find(id);
            if (reference == null)
            {
                return HttpNotFound();
            }
            return View(reference);
        }

        // POST: beheer/referenties/wijzigen/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("wijzigen/{id:int}")]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,URL,ImagePath,CreatedAt,UpdatedAt")] Reference reference, HttpPostedFileBase ImagePath)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reference).State = EntityState.Modified;
                db.Entry(reference).Property(x => x.ImagePath).IsModified = false;
                db.Entry(reference).Property(x => x.CreatedAt).IsModified = false;


                var dbReference = db.References.Where(x => x.Id == reference.Id).SingleOrDefault();
                string oldImagePath = dbReference.ImagePath;

                if (ImagePath != null)
                {
                    // generate random guid string as fileName
                    Guid g = Guid.NewGuid();
                    string fileName = Convert.ToBase64String(g.ToByteArray());
                    fileName = fileName.Replace("=", "");
                    fileName = fileName.Replace("+", "");
                    fileName = fileName.Replace("/", "");
                    fileName = fileName + "-reference" + Path.GetExtension(ImagePath.FileName);

                    // delete old image
                    oldImagePath = Request.MapPath("~/UploadedFiles/ReferenceImages" + oldImagePath);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                    // save image
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles/ReferenceImages"), fileName);
                    ImagePath.SaveAs(path);

                    // set properties
                    reference.ImagePath = fileName;
                }

                // set dates
                reference.UpdatedAt = DateTime.Now;

                // remove http:// or https:// from posted URL
                reference.URL = reference.URL.Replace("https://", "").Replace("http://", "");

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reference);
        }

        // GET: beheer/referenties/verwijderen/5
        [Route("verwijderen/{id:int}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reference reference = db.References.Find(id);
            if (reference == null)
            {
                return HttpNotFound();
            }
            return View(reference);
        }

        // POST: beheer/referenties/verwijderen/5
        [Route("verwijderen/{id:int}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reference reference = db.References.Find(id);
            db.References.Remove(reference);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CeeLearnAndDo/Views/AdminReferences/Create.cshtml
@model CeeLearnAndDo.Models.Reference

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Referentiebeheer</h2>


@using (Html.BeginForm("Create", "AdminReferences", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nieuwe referentie</h4>

        <div class="d-flex flex-row">
            <div class="p-2">
                <small>
                    <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
                </small>
            </div>
        </div>

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hr />

<div class="d-flex flex-row">
    <div class="p-2">
        <small>
            <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
        </small>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CeeLearnAndDo/Views/AdminReferences/Delete.cshtml
@model CeeLearnAndDo.Models.Reference

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Title) + " verwijderen";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Verwijderen</h2>

<div class="alert alert-danger" role="alert">
    Weet je zeker dat je deze referentie wilt <strong>verwijderen</strong>?<br />
    <input type="submit" value="Verwijderen" class="btn btn-danger" />
</div>

<div class="d-flex flex-row">
    <div class="p-2">
        <small>
            <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
        </small>
    </div>
    <div class="p-2 ml-auto">
        <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
    </div>
</div>

<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img class="edit-img" src="~/UploadedFiles/ReferenceImages/@Html.DisplayFor(model => model.ImagePath)" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>

CeeLearnAndDo/Views/AdminReferences/Details.cshtml
@model CeeLearnAndDo.Models.Reference

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Reference</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @if (Model.Description.Length > 20)
            {
                @Model.Description.Substring(0, 20)...
                }
            else
            {
                @Html.DisplayFor(model => model.Description)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CeeLearnAndDo/Views/AdminReferences/Edit.cshtml
@model CeeLearnAndDo.Models.Reference

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Title) + " Wijzigen";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Referentiebeheer</h2>


@using (Html.BeginForm("Edit", "AdminReferences", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Referentie wijzigen</h4>

        <div class="d-flex flex-row">
            <div class="p-2">
                <small>
                    <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
                </small>
            </div>
            <div class="p-2 ml-auto">
                <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
            </div>
        </div>

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img class="edit-img" src="~/UploadedFiles/ReferenceImages/@Html.DisplayFor(model => model.ImagePath)" />
                <hr />
                Nieuwe afbeelding toevoegen
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="d-flex flex-row">
    <div class="p-2">
        <small>
            <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
        </small>
    </div>
    <div class="p-2 ml-auto">
        <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CeeLearnAndDo/Views/AdminReferences/Index.cshtml
@model IEnumerable<CeeLearnAndDo.Models.Reference>

@{
    ViewBag.Title = "Referentiebeheer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Referentiebeheer</h2>

<p>
    @Html.ActionLink("Nieuwe referentie", "Create", null, new { @class = "btn btn-success" })
</p>

<section class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="card col-md-3" style="min-width: 286px; margin: 10px">
                <a title="Ga naar '@Html.DisplayFor(modelItem => item.URL)'" : href="http://@Html.DisplayFor(modelItem => item.URL)" target="_blank">
                    <img class="card-img-top" src="~/UploadedFiles/ReferenceImages/@Html.DisplayFor(modelItem => item.ImagePath)" />
                </a>
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                    <p class="card-text" title="@Html.DisplayFor(modelItem => item.Description)">
                        @if (item.Description.Length > 20)
                        {
                            @item.Description.Substring(0, 20)<span>...</span>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Description)
                        }
                    </p>
                    <a title="Bekijken" href="@Url.Action("Details", new { id = item.Id })" class="btn btn-primary"><i class="fas fa-eye"></i></a>
                    <a title="Wijzigen" href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-info"><i class="fas fa-edit"></i></a>
                    <a title="Verwijderen" href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                </div>
            </div>
        }
    </div>
</section>