CeeLearnAndDo/Controllers/AdminArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CeeLearnAndDo.Models;
using System.IO;

namespace CeeLearnAndDo.Controllers
{
    [RoutePrefix("beheer/artikelen")]
    [Route("{action=index}")]
    public class AdminArticlesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: beheer/artikelen
        [Authorize]
        public ActionResult Index()
        {
            var articles = from a in db.Articles
                           select a;

            articles = articles.OrderByDescending(s => s.UpdatedAt);

            return View(articles.ToList());
        }

        // GET: beheer/artikelen/5
        [Route("{id}")]
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // Upload image
        [HttpPost]
        [Authorize]
        public string UploadImage()
        {
            string fileName = "";
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];

                // generate random guid string as fileName
                Guid g = Guid.NewGuid();
                fileName = Convert.ToBase64String(g.ToByteArray());
                fileName = fileName.Replace("=", "");
                fileName = fileName.Replace("+", "");
                fileName = fileName.Replace("/", "");
                fileName = fileName + "-article" + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/UploadedFiles/ArticleImages"), fileName);
                file.SaveAs(path);
            }
            return "/UploadedFiles/ArticleImages/" + fileName;
        }

        // GET: beheer/artikelen/nieuw
        [Route("nieuw")]
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: beheer/artikelen/nieuw
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("nieuw")]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Title,Description,Content,ImagePath,Approved,CreatedAt,UpdatedAt")] Article article, HttpPostedFileBase ImagePath)
        {
            if (ModelState.IsValid)
            {

                // generate random guid string as fileName
                Guid g = Guid.NewGuid();
                string fileName = Convert.ToBase64String(g.ToByteArray());
                fileName = fileName.Replace("=", "");
                fileName = fileName.Replace("+", "");
                fileName = fileName.Replace("/", "");
                fileName = fileName + "-article" + Path.GetExtension(ImagePath.FileName);

                // save image
                string path = Path.Combine(Server.MapPath("~/UploadedFiles/ArticleImages"), fileName);
                ImagePath.SaveAs(path);
                article.ImagePath = fileName;

                // add article properties
                db.Articles.Add(article);

                // set approved false
                article.Approved = false;

                // at dates
                article.CreatedAt = DateTime.Now;
                article.UpdatedAt = DateTime.Now;

                // save new article
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(article);
        }

        // GET: beheer/artikelen/wijzigen/5
        [Route("wijzigen/{id:int}")]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: beheer/artikelen/wijzigen/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("wijzigen/{id:int}")]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,Content,ImagePath,Approved,CreatedAt,UpdatedAt")] Article article, HttpPostedFileBase ImagePath)
        {
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.Entry(article).Property(x => x.ImagePath).IsModified = false;
                db.Entry(article).Property(x => x.CreatedAt).IsModified = false;

                var dbArticle = db.Articles.Where(x => x.Id == article.Id).SingleOrDefault();
                string oldImagePath = dbArticle.ImagePath;

                if (ImagePath != null)
                {

                    // generate random guid string as fileName
                    Guid g = Guid.NewGuid();
                    string fileName = Convert.ToBase64String(g.ToByteArray());
                    fileName = fileName.Replace("=", "");
                    fileName = fileName.Replace("+", "");
                    fileName = fileName.Replace("/", "");
                    fileName = fileName + "-article" + Path.GetExtension(ImagePath.FileName);

                    // delete old image
                    oldImagePath = Request.MapPath("~/UploadedFiles/ArticleImages" + oldImagePath);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                    // save image
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles/ArticleImages"), fileName);
                    ImagePath.SaveAs(path);

                    // set properties
                    article.ImagePath = fileName;
                }

                // set dates
                article.UpdatedAt = DateTime.Now;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: beheer/artikelen/verwijderen/5
        [Route("verwijderen/{id:int}")]
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: beheer/artikelen/verwijderen/5
        [Route("verwijderen/{id:int}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CeeLearnAndDo/Views/AdminArticles/Create.cshtml
@model CeeLearnAndDo.Models.Article

@{
    ViewBag.Title = "Nieuwe artikel";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Artikelen-databank</h2>


@using (Html.BeginForm("Create", "AdminArticles", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nieuwe artikel</h4>

        <div class="d-flex flex-row">
            <div class="p-2">
                <small>
                    <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
                </small>
            </div>
        </div>

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @id = "summernote", @rows = 10 }})
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hr />

<div class="d-flex flex-row">
    <div class="p-2">
        <small>
            <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
        </small>
    </div>
</div>
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CeeLearnAndDo/Views/AdminArticles/Delete.cshtml
@model CeeLearnAndDo.Models.Article

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Title) + " verwijderen";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Verwijderen</h2>

<div class="alert alert-danger" role="alert">
    Weet je zeker dat je dit artikel wilt <strong>verwijderen</strong>?<br />
    <input type="submit" value="Verwijderen" class="btn btn-danger" />
</div>

<!-- Header -->
<header class="masthead article-image bg-primary text-white text-center" style="background-image: url(/UploadedFiles/ArticleImages/@Html.DisplayFor(model => model.ImagePath))">
    <div class="container" style="text-shadow: 1px 1px 1px black">
        <h1 class="mb-0">@Html.DisplayFor(model => model.Title)</h1>
        <p class="font-weight-light mb-0">@Html.DisplayFor(model => model.Description)</p>
    </div>
</header>
<section class="bg-about text-black mb-0" id="about">
    <div class="d-flex flex-row">
        <div class="p-2">
            <small>
                <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
            </small>
        </div>
        <div class="p-2 ml-auto">
            <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
        </div>
    </div>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @Html.Raw(Model.Content)
            </div>
        </div>
    </div>
    <hr />
    <div class="d-flex flex-row">
        <div class="p-2">
            <small>
                <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
            </small>
        </div>
        <div class="p-2 ml-auto">
            <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
        </div>
    </div>
</section>

CeeLearnAndDo/Views/AdminArticles/Details.cshtml
@model CeeLearnAndDo.Models.Article

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Title);
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Header -->
<header class="masthead article-image bg-primary text-white text-center" style="background-image: url(/UploadedFiles/ArticleImages/@Html.DisplayFor(model => model.ImagePath))">
    <div class="container" style="text-shadow: 1px 1px 1px black">
        <h1 class="mb-0">@Html.DisplayFor(model => model.Title)</h1>
        <p class="font-weight-light mb-0">@Html.DisplayFor(model => model.Description)</p>
    </div>
</header>
<section class="bg-about text-black mb-0" id="about">
    <div class="d-flex flex-row">
        <div class="p-2">
            <small>
                <a href="@Url.Action("Edit", new { id = Model.Id })"><i class="far fa-edit"></i> Wijzigen</a>
            </small>
        </div>
        <div class="p-2">
            <small>
                <a href="@Url.Action("Delete", new { id = Model.Id })"><i class="far fa-trash-alt"></i> Verwijderen</a>
            </small>
        </div>
        <div class="p-2">
            <small>
                <a href="@Url.Action("Edit", new { id = Model.Id })"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
            </small>
        </div>
        <div class="p-2 ml-auto">
            <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
        </div>
    </div>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @Html.Raw(Model.Content)
            </div>
        </div>
    </div>
    <hr />
    <div class="d-flex flex-row">
        <div class="p-2">
            <small>
                <a href="@Url.Action("Edit", new { id = Model.Id })"><i class="far fa-edit"></i> Wijzigen</a>
            </small>
        </div>
        <div class="p-2">
            <small>
                <a href="@Url.Action("Delete", new { id = Model.Id })"><i class="far fa-trash-alt"></i> Verwijderen</a>
            </small>
        </div>
        <div class="p-2">
            <small>
                <a href="@Url.Action("Index", new { id = Model.Id })"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
            </small>
        </div>
        <div class="p-2 ml-auto">
            <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
        </div>
    </div>
</section>

CeeLearnAndDo/Views/AdminArticles/Edit.cshtml
@model CeeLearnAndDo.Models.Article

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Artikelen-databank</h2>

@using (Html.BeginForm("Edit", "AdminArticles", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artikel wijzigen</h4>


        <div class="d-flex flex-row">
            <div class="p-2">
                <small>
                    <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
                </small>
            </div>
            <div class="p-2 ml-auto">
                <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
            </div>
        </div>


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @id = "summernote", @rows = 10 } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="d-flex flex-row">
    <div class="p-2">
        <small>
            <a href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> Terug naar het overzicht</a>
        </small>
    </div>
    <div class="p-2 ml-auto">
        <small>Laatst gewijzigd op: <strong>@Html.DisplayFor(model => model.UpdatedAt)</strong></small>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CeeLearnAndDo/Views/AdminArticles/Index.cshtml
@model IEnumerable<CeeLearnAndDo.Models.Article>

@{
    ViewBag.Title = "Artikelen-databank";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Artikelen-databank</h2>

<p>
    @Html.ActionLink("Nieuwe artikel", "Create", null, new { @class = "btn btn-success" })
</p>
@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approved)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedAt)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImagePath)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Approved)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedAt)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>*@

@foreach (var item in Model)
{
    <div class="list-group">
        <a href="@Url.Action("Details", new { id = item.Id })" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="row">
                <div class="col-md-3">
                    <img class="card-img-top" src="~/UploadedFiles/ArticleImages/@Html.DisplayFor(modelItem => item.ImagePath)" />
                </div>
                <div class="col-md-9">
                    <div class="d-flex w-100 justify-content-between">
                        <h2 class="mb-1">@Html.DisplayFor(modelItem => item.Title)</h2>
                        <small style="text-align: right;">
                            @Html.DisplayFor(modelItem => item.UpdatedAt)<br/>
                            @{
                                if (item.Approved)
                                {
                                    <i>Goedgekeurd</i>
                                }
                                else
                                {
                                    <i>Nog niet goedgekeurd</i>
                                }
                            }
                        </small>
                    </div>
                    <p class="mb-1">
                        @if (item.Description.Length > 100)
                        {
                            @item.Description.Substring(0, 100)<span>...</span>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Description)
                        }
                    </p>


                </div>

            </div>

        </a>

    </div>
                        }